### ISSUE TITLE
Not an issue, but a question...

### ISSUE THREAD

**Issue by sauerlu** [nao-pon/flysystem-google-drive#1]
Dear sir,
I don't know if it's the right place, to ask (if not you can delete this post).
I'm a Newbee with Elfinder, and I want to add to map (in Elfinder 2.1.7) a shared directory of my google drive. I've read your instructions, but I can't follow. 

In the composer I've added:

` "require": {
        "php": ">=5.2"
       "barryvdh/elfinder-flysystem-driver"
       "nao-pon/flysystem-google-drive"`

Where do I have to put the flysystem-google-drive directory (in the elfinder root?)

And then I don't know how to continue... Sorry.

Can you please provide me some help?
Thanks for your patience.
F.

**Comment by nao-pon** [comment]
@sauerlu I recommend to composer.json for test
```json
{
    "require": {
        "league/flysystem": "1.1.*@dev",
        "barryvdh/elfinder-flysystem-driver": "~0.1@dev",
        "nao-pon/flysystem-google-drive": "~1.1@dev",
        "google/apiclient": "@rc"
    }
}
```

**Comment by sauerlu** [comment]
Hi, thanks a lot for your fast answer.

I've copied the content of "flysystem-google-drive-master" into my "elfinder" directory and I've used your require code above.
My elfinder folder looks like this now:
[elfinderfolder](http://screencast.com/t/zzaTu0Ne20W)

What exactly must i do now please?

**Comment by nao-pon** [comment]
> I've copied the content of "flysystem-google-drive-master" into my "elfinder" directory

It does not need. You should be set up to use the composer at the server shell.

**Comment by sauerlu** [comment]
Thanks but how and where can  i make the needed settings please.
Sorry for anoying you sir...

**Comment by sauerlu** [comment]
Okay sorry, I'm too stupid for that. I'll try to find an other possibility :)
Thank you sir!

**Comment by sauerlu** [comment]
My connector.php looks like this:

`<?php

defined( '_JEXEC' ) or die;
error_reporting(0); // Set E_ALL for debuging

include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinderConnector.class.php';
include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinder.class.php';
include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinderVolumeDriver.class.php';
include_once JPATH_ROOT.'/plugins/editors/yeeditor/assets/js/ckeditor/elfinder/php/'.'elFinderVolumeLocalFileSystem.class.php';
// Required for MySQL storage connector
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeMySQL.class.php';
// Required for FTP connector support
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';


/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from  '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
	return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
		? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
		:  null;                                    // else elFinder decide it itself
}

//Get select image folder by option
$elfinderfolderaccess = array_filter(json_decode(get_yeeditor_option('yeeditor_elfinderfolderaccess','[]'),true));
$user = JFactory::getUser();
$imagefolder = "images/";
foreach($user->groups as $group){
	if(isset($elfinderfolderaccess[$group])){
		$imagefolder = $elfinderfolderaccess[$group]."/";
	}
}

$opts = array(
	// 'debug' => true,
	'roots' => array(
		array(
			'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
			'path'          => JPATH_ROOT.'/'.$imagefolder,         // '../files/',         // path to files (REQUIRED)
			'URL'           => JURI::root().$imagefolder,        //dirname($_SERVER['PHP_SELF']) . '/../files/',  // URL to files (REQUIRED)
			'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
			'mimeDetect'    => 'mime_content_type',
			'uploadDeny'    => array('text/x-php'),
			'disabled' => array('mkfile', 'edit')
		)
	)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
`

and the composer.json (in the elfinder/php folder) like this:

`{
    "name": "nao-pon/flysystem-google-drive",
    "description": "Flysystem adapter for Google Drive",
    "license": "MIT",
    "authors": [
        {
            "name": "Naoki Sawada",
            "email": "hypweb@gmail.com"
        }
    ],
       "require": {
        "league/flysystem": "1.1.*@dev",
        "barryvdh/elfinder-flysystem-driver": "~0.1@dev",
        "nao-pon/flysystem-google-drive": "~1.1@dev",
        "google/apiclient": "@rc"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "mockery/mockery": "0.9.*"
    },
    "autoload": {
        "psr-4": {
            "Hypweb\\Flysystem\\GoogleDrive\\": "src/"
        }
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "branch-alias": {
            "dev-api_v2": "1.0-dev",
            "dev-master": "1.1-dev"
        }
    }
}
`

**Comment by nao-pon** [comment]
**ON YOUR SERVER SHELL**
```sh
cd [Your connector.php directory]
curl -sS https://getcomposer.org/installer | php
php composer.phar require league/flysystem:1.1.*@dev league/flysystem-cached-adapter:dev-master@dev barryvdh/elfinder-flysystem-driver:0.1.*@dev nao-pon/flysystem-google-drive:1.1.*@dev google/apiclient:@rc
```
AND edit your connector.php
```php
defined( '_JEXEC' ) or die;
error_reporting(0); // Set E_ALL for debuging

include_once './vendor/autoload.php';

/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from  '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
    return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
        ? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
        :  null;                                    // else elFinder decide it itself
}

//Get select image folder by option
$elfinderfolderaccess = array_filter(json_decode(get_yeeditor_option('yeeditor_elfinderfolderaccess','[]'),true));
$user = JFactory::getUser();
$imagefolder = "images/";
foreach($user->groups as $group){
    if(isset($elfinderfolderaccess[$group])){
        $imagefolder = $elfinderfolderaccess[$group]."/";
    }
}

$opts = array(
    // 'debug' => true,
    'roots' => array(
        array(
            'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
            'path'          => JPATH_ROOT.'/'.$imagefolder,         // '../files/',         // path to files (REQUIRED)
            'URL'           => JURI::root().$imagefolder,        //dirname($_SERVER['PHP_SELF']) . '/../files/',  // URL to files (REQUIRED)
            'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
            'mimeDetect'    => 'mime_content_type',
            'uploadDeny'    => array('text/x-php'),
            'disabled' => array('mkfile', 'edit')
        )
    )
);

$client->setClientId('[YOUR CLIENTID]');
$client->setClientSecret('[YOUR CLIENTSECRET]');
$client->refreshToken('[YOUR REFRESH TOKEN]');

$service = new \Google_Service_Drive($client);

$googleDrive = new \Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter($service, 'root', [ 'useHasDir' => true ]);

$filesystem = new \League\Flysystem\Filesystem($googleDrive);

$opts['roots'][] = [
    'driver' => 'Flysystem',
    'alias'  => 'GoogleDrive flysystem',
    'filesystem' => $filesystem
];

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

**Comment by sauerlu** [comment]
Thanks sir, for you amazing support, I really appreciate that!
- I've installed the composer in the connector.php directory
- I started the comper over my server shell (xampp win10)
- When I copied the code `php composer.phar require league/flysystem:1.1.*@dev league/flysystem-cached-adapter:dev-master@dev barryvdh/elfinder-flysystem-driver:0.1.*@dev nao-pon/flysystem-google-drive:1.1.*@dev google/apiclient:@rc`

I got this message:

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

[Composer\Downloader\TransportException]
The "http://packagist.org/p/league/flysystem%24bc7d13f42505d592c5e9bb2dc145ef92806bec4881f800d68a45a1ab7f3548a7.json" file could not be downloaded: failed to open stream: HTTP request failed!

As your wrote above, I've updated my connector.php
I've found the ClientId and ClientSecret, but how can i find/get the refreshToken Please?

Thanks a lot for your great support.

**Comment by nao-pon** [comment]
> file could not be downloaded: failed to open stream: HTTP request failed!

Are enabled `curl` and `openssl` of PHP? OR Plz check your firewall.

>  how can i find/get the refreshToken

Please ask to teacher [Google](https://www.google.com/search?q=google+api+get+refreshToken).

**Comment by sauerlu** [comment]
Again Thanks a lot...

For the refresh token It's ok thank you.
Curl and openssl are enabled. Firewall is disable.

Now I get the following message in my server shell:

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package nao-pon/flysystem-google-drive No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
Sorry...
Thank you.

**Comment by nao-pon** [comment]
Either install [git](https://git-for-windows.github.io/), or set up to stable version with `php composer.phar require league/flysystem league/flysystem-cached-adapter barryvdh/elfinder-flysystem-driver nao-pon/flysystem-google-drive google/apiclient`.
