### ISSUE TITLE
How To make Unit Tests with Storage('google') mocked?

### ISSUE THREAD

**Issue by sr2ds** [nao-pon/flysystem-google-drive#109]
Hello,

How to do my unit tests run with not real google drive connection to best perform? Has some some example to this?

Or anybody can help me with tips?

Thanks

**Comment by PaolaRuby** [comment]
This package has no support since  [29 Jul 2020](https://github.com/nao-pon/flysystem-google-drive/commit/bb812339ecf06540ed096f71403f10fcbcc590f3)

**Comment by sr2ds** [comment]
> This package has no support since [29 Jul 2020](https://github.com/nao-pon/flysystem-google-drive/commit/bb812339ecf06540ed096f71403f10fcbcc590f3)

Thanks for answer, which package are you using now?

**Comment by PaolaRuby** [comment]
[masbug/flysystem-google-drive-ext](https://github.com/masbug/flysystem-google-drive-ext)
