### ISSUE TITLE
getting no results from teamdrive folders

### ISSUE THREAD

**Issue by abdulqadir555** [nao-pon/flysystem-google-drive#114]
this was my code

`    
Route::get('list', function() {

    $dir = '0AOKPy-Y1ZWZ2Uk9PVA';
    $recursive = false; // Get subdirectories also?
    $contents = collect(Storage::cloud()->listContents($dir, $recursive));

    // return $contents->where('type', '=', 'dir'); // directories
    return $contents->where('type', '=', 'file'); // files
});
`

this was result

![image](https://user-images.githubusercontent.com/93119677/179417685-cc0f2269-34cb-46f5-a557-5b1b31713250.png)

**Comment by abdulqadir555** [comment]
> this was my code
> 
> ` Route::get('list', function() {
> 
> ```
> $dir = '0AOKPy-Y1ZWZ2Uk9PVA';
> $recursive = false; // Get subdirectories also?
> $contents = collect(Storage::cloud()->listContents($dir, $recursive));
> 
> // return $contents->where('type', '=', 'dir'); // directories
> return $contents->where('type', '=', 'file'); // files
> ```
> 
> }); `
> 
> this was result
> 
> ![image](https://user-images.githubusercontent.com/93119677/179417685-cc0f2269-34cb-46f5-a557-5b1b31713250.png)

I found a solution
I added team drive id here  "GoogleDriveAdapter.php"
![image](https://user-images.githubusercontent.com/93119677/179417882-7bbe0e8c-2253-4c13-9a37-2226d7d7d2ff.png)


and it was successfull

![image](https://user-images.githubusercontent.com/93119677/179417956-dc4d1d92-f154-48df-91bd-fd8b7ad79eb2.png)


hope it helps someone

**Comment by PaolaRuby** [comment]
It is no a good idea changing vendor files, you have to put that on a service provider
https://github.com/ivanvermeyen/laravel-google-drive-demo#i-took-care-of-this
