### ISSUE TITLE
GetItems Recursive

### ISSUE THREAD

**Issue by tjhorlacher** [nao-pon/flysystem-google-drive#14]
Looks like in GoogleDriveAdaptor: line 850. Need to prepend $dirname to $id. Otherwise recursive lookup not working. E.g. currently it's just passing $id of the obj to next getItems read.

Please advise, otherwise will fork.

Thanks, nice work!

**Comment by wiljonlim** [comment]
Hi, I am having the same issue.
I replace $id with $result['path'] to fix the issue.

Thank you.

**Comment by nao-pon** [comment]
@wiljonlim Yes! You are right. so I'll fix it. Thanks!

**Comment by nao-pon** [comment]
@tjhorlacher , @wiljonlim Thanks! 👍
