### ISSUE TITLE
The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 8192 bytes, which does not meet this requirement..

### ISSUE THREAD

**Issue by semsphy** [nao-pon/flysystem-google-drive#15]
I'm using your package in `laravel-backup`, it uses `writeStream` method to upload a zip file to Google drive. And the file size is 4MB. 

After run a backup command I got error messages: 

```
The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 8192 bytes, which does not meet this requirement..
```

But if I upload file with this snippet, it is ok.

```php
\Storage::disk('google')->put('2017-06-02-20-23-34.zip', file_get_contents('../2017-06-02-20-23-34.zip'));
```
Are there any solutions?

**Comment by greatsami** [comment]
Did you find a solution ???

**Comment by vitorfavila** [comment]
Same problem here!

**Comment by nao-pon** [comment]
@semsphy , @greatsami , @vitorfavila What is result of `ini_get('memory_limit')` on PHP?

**Comment by nao-pon** [comment]
There was a problem when PHP memory_limit was -1, so I fixed it. Thanks!

**Comment by vitorfavila** [comment]
@nao-pon memory_limit is -1

There is a problem with this setting?

**Comment by vitorfavila** [comment]
@nao-pon Thank you!!!

**Comment by semsphy** [comment]
Thanks
