### ISSUE TITLE
(1/1) ErrorException A non well formed numeric value encountered

### ISSUE THREAD

**Issue by hectorda** [nao-pon/flysystem-google-drive#17]
Hi i am using Laravel With PHP 7.1 and when I try to upload a File This Error Ocurres
![captura](https://user-images.githubusercontent.com/11987225/28926123-e3ef02ee-7834-11e7-8a38-5b3b877bcb4b.PNG)

The Filesize is about 2KB.

In PHP 7.0 i dont have any troubles.

**Comment by hectorda** [comment]
The Problem is the Operation $val *= 1024 in PHP 7.1 we need cast the value to a Number Format.
like  `$val = (float)trim($val, "bB \t\n\r\0\x0B");`

**Comment by nao-pon** [comment]
@hectorda Thanks! 👍
