### ISSUE TITLE
can u help me?

### ISSUE THREAD

**Issue by tkmine** [nao-pon/flysystem-google-drive#18]
can u help me? 
![untitsled](https://user-images.githubusercontent.com/26906261/29034196-b4e6232a-7bc1-11e7-858c-350ded972b1b.png)

**Comment by samuelyeshua** [comment]
[StackOverflow](https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate)
