### ISSUE TITLE
Is a video overplayed?

### ISSUE THREAD

**Issue by eissasoubhi** [nao-pon/flysystem-google-drive#20]
Hello, 

is it possible to know if a google drive video is overplayed?
I'm using google drive videos on my blog using PHP, and I want to know if a video is overplayed (when the message **"Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later."** shows up instead of playing the video).

example of a google drive video: https://docs.google.com/file/d/____fileid____/preview

is there any way to do that?

Thanks.

**Comment by nao-pon** [comment]
@eissasoubhi Google Drive API can not to know that video is overplayed. So I think it is impossible.
