### ISSUE TITLE
How to get the Google Drive service to access the API

### ISSUE THREAD

**Issue by Unemployed** [nao-pon/flysystem-google-drive#24]
The Google Drive service is protected inside the adapter so here is the extension to retrieve the API service. I assumed that we shouldn't modify the adapter because that is outside it's usual purpose.

I needed the service to change file permissions inside Google Drive, and retrieve other API resources. Why tear my hair out and create another service provider? This will retrieve the `Google_Service_Drive` object.

```php
class GoogleDriveAdapter extends \Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter {
    
    public function __construct(\Google_Service_Drive $service, $root = null, $options = array())
    {
        parent::__construct($service, $root, $options);
    }

    public function getService()
    {
            return $this->service;
    }
}
```

I highly recommend using @ivanvermeyen's [service provider](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/master/app/Providers/GoogleDriveServiceProvider.php) if you are using laravel. Just replace Flysystem's adapter with the one above.

**Comment by nao-pon** [comment]
@Unemployed Thanks! 👍
