### ISSUE TITLE
How do you 'auto-create' the directory?

### ISSUE THREAD

**Issue by jptlightx005** [nao-pon/flysystem-google-drive#27]
I hope this repository is still active. Example below:

    Storage::disk('google')->put('unexisting-folder/existing-file.' . $ext, file_get_contents($file));

I get the error

    { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "File not found: unexisting-folder.", "locationType": "parameter", "location": "fileId" } ], "code": 404, "message": "File not found: unexisting-folder." } }

So, is it possible to automatically create the 'unexisting-folder'? Or maybe I can check if it exists then create it? Thanks!

**Comment by nao-pon** [comment]
@jptlightx005 GoogleDrive is not a directory structure unlike a general file system, but a file system by item ID. It allows you to have the same item name with the same parent.

Therefore, it can not fully correspond to FlySystem's API (automatic directory creation).

Thanks.
