### ISSUE TITLE
normaliseObject() should include the unmolested filename

### ISSUE THREAD

**Issue by Bilge** [nao-pon/flysystem-google-drive#34]
It seems `normaliseObject()` takes the liberty of splitting the file name into `'filename'` and `'extension'` parts, but this often places a burden on the caller to do the same when wishing to perform a filename comparison. The Google API returns the complete file name, and this should be exposed by the adapter, to make it easier to match on complete file names.

**Comment by nao-pon** [comment]
Closes by #35.
