### ISSUE TITLE
getMetadata() does not return complete information

### ISSUE THREAD

**Issue by Bilge** [nao-pon/flysystem-google-drive#37]
Comparing the information available for files fetched from `listContents()` and `getMetadata()` shows alarming inconsistencies which can be difficult to work around. Specifically, `getMetadata()` is inferior because of the following behaviours:

* `dirname` property is missing
* `basename` property is missing
* `path` does not show a slash (`/`)-separated folder hierarchy; instead just shows a last parent node id.

`listContents()` and `getMetadata()` should return the same data in the same, consistent format.

**Comment by nao-pon** [comment]
@Bilge The `dirname` and `basename` properties are not included in the return value of the `listContents()` function of the GoogleDrive adapter. It is attached by FlySystem after that.

The value of `path` is calculated from the value passed to `getMetadata()`. Please include the hierarchical structure in the passed value.

**Comment by Bilge** [comment]
Thanks @nao-pon, I was able to resolve my issue by passing around `path` instead of `basename` identifiers.
