### ISSUE TITLE
when connected google drive and create new folder ! and upload file to new folder, it moved to root path

### ISSUE THREAD

**Issue by afterdead** [nao-pon/flysystem-google-drive#4]
when connected google drive, -> create new folder with elfilder and upload file to new folder, it moved to root path how to slove this ,

**Comment by nao-pon** [comment]
@afterdead Please try `composer update` and use 'FlysystemExt' driver. (I edited [README.md](https://github.com/nao-pon/flysystem-google-drive/blob/master/README.md#usage-to-with-elfinder))

**Comment by afterdead** [comment]
thank you for response sir i'll try. ^^ ,

**Comment by afterdead** [comment]
i try but still moved,
1. i composer update it said "nothing to install or update" i think because i installed yesterday.
2. changed drive to 'FlysystemExt', 
but it still move to root path. T_T
MY COMPOSER.json 
```
{
    "require": {
        "nao-pon/flysystem-google-drive": "~1.1",
        "nao-pon/elfinder-flysystem-driver-ext": "^1.0"
    }
}
```

**Comment by nao-pon** [comment]
umm...

What is add `'cacheDisableEnsureParentDirectories' => true` to volume option. 
```php
$gdrive = [
    'driver'       => 'FlysystemExt',
    'alias'        => 'GoogleDrive',
    'rootCssClass' => 'elfinder-navbar-root-googledrive',
    'filesystem'   =>  new \League\Flysystem\Filesystem($adapter),
    'fscache'      => $cache,
    'cacheDisableEnsureParentDirectories' => true
];
```

OR set un-use cache. (`$useCache = false;`)

**Comment by afterdead** [comment]
i try with stop cache it still ca'nt work.
`'cacheDisableEnsureParentDirectories' => true 
`and 
`$useCache = false;
`

what i should scope of API TOKEN sir ? 
now iscope with 
`$client->setScopes(array('https://www.googleapis.com/auth/userinfo.profile  https://www.googleapis.com/auth/drive  https://www.googleapis.com/auth/drive.file  https://www.googleapis.com/auth/drive.metadata'));`

**Comment by nao-pon** [comment]
> what i should scope of API TOKEN sir ?

It require `Google_Service_Drive::DRIVE`. Another scopes are optional.

**Comment by nao-pon** [comment]
@afterdead I got it! I guess your server is windows. so please add volume option `'separator' => '/',`.
e.g.
```php
// Google Drive elFinder Volume driver
$gdrive = [
    'driver'       => 'FlysystemExt',
    'alias'        => 'GoogleDrive',
    'separator'    => '/',
    'rootCssClass' => 'elfinder-navbar-root-googledrive',
    'filesystem'   =>  new \League\Flysystem\Filesystem($adapter),
    'fscache'      => $cache,
    'cacheDisableEnsureParentDirectories' => true
];
```

I edited README.md. Thanks! :+1:

**Comment by afterdead** [comment]
hola!!  tank you sir That Great !

**Comment by nao-pon** [comment]
@afterdead sorry, `'cacheDisableEnsureParentDirectories' => true` is unneeded. 

```php
// Google Drive elFinder Volume driver
$gdrive = [
    'driver'       => 'FlysystemExt',
    'alias'        => 'GoogleDrive',
    'separator'    => '/',
    'rootCssClass' => 'elfinder-navbar-root-googledrive',
    'filesystem'   =>  new \League\Flysystem\Filesystem($adapter),
    'fscache'      => $cache
];
```

**Comment by afterdead** [comment]
i have some little question about composer and this package.

i try to use this command 

`composer require nao-pon/flysystem-google-drive:~1.1`

on the laravel 4.2.x folder 
and it told

>   Problem 1
    - Installation request for phpseclib/phpseclib (locked at 0.3.10) -> satisfiable by phpseclib/phpseclib[0.3.10].
    - Installation request for guzzlehttp/psr7 (locked at 1.3.1) -> satisfiable by guzzlehttp/psr7[1.3.1].
    - Conclusion: don't install google/apiclient v2.0.1
    - nao-pon/flysystem-google-drive 1.1.0 requires google/apiclient ^2.0@dev -> satisfiable by google/apiclient[v2.0.0, v2.0.1].
    - nao-pon/flysystem-google-drive 1.1.1 requires google/apiclient ^2.0@dev -> satisfiable by google/apiclient[v2.0.0, v2.0.1].
    - nao-pon/flysystem-google-drive 1.1.2 requires google/apiclient ^2.0 -> satisfiable by google/apiclient[v2.0.0, v2.0.1].
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8].
    - Conclusion: don't install google/auth v0.8
    - Installation request for nao-pon/flysystem-google-drive ~1.1 -> satisfiable by nao-pon/flysystem-google-drive[1.1.0, 1.1.1, 1.1.2].

what can i do for slove this problem , I try to find about other answer on stackoverflow but i don't understand thank you for you help sir.

**Comment by nao-pon** [comment]
@afterdead I checked on PHP 5.4.31, 5.5.36, 5.6.23 and 7.0.5. There are no problems.
