### ISSUE TITLE
Why use teamDriveID as root?

### ISSUE THREAD

**Issue by tobias-kuendig** [nao-pon/flysystem-google-drive#41]
What's the reason that the `teamDriveID` is set as root here?

https://github.com/nao-pon/flysystem-google-drive/blob/54e77353d9553568fc9f19602d3baae3cc60d6e3/src/GoogleDriveAdapter.php#L1293

This way all files go into the root directory of my team drive by default. But what if I want to use the specified `root_folder_id` directory from the constructor that is within my team drive as parent?

**Comment by tobias-kuendig** [comment]
This is looking good and works! See #42

**Comment by nao-pon** [comment]
@tobias-kuendig Thanks! 👍
