### ISSUE TITLE
deleting files actually moves them to trash, is there a way to actually delete them completely?

### ISSUE THREAD

**Issue by Jossnaz** [nao-pon/flysystem-google-drive#48]
deleting files actually moves them to trash, is there a way to actually delete them completely?

**Comment by Jossnaz** [comment]
from https://github.com/private-it/flysystem-google-drive/issues/4

**Comment by nao-pon** [comment]
@Jossnaz I'll make an option to delete or into trash can be chosen.

Thanks! 👍

**Comment by nao-pon** [comment]
@Jossnaz "deleteAction" was added to the option specified by the third argument when creating the adapter.

```php
$googleDrive = new Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter(
	new \Google_Service_Drive($client), // Client service
	'root',                             // Folder ID as root ('root' or Folder ID)
	[ 'deleteAction' => 'delete' ]      // Delete action 'trash' (Into trash) or 'delete' (Permanently delete)
);
```
