### ISSUE TITLE
This plugin uses Google plus Sign-In Or Google Sign-In ?

### ISSUE THREAD

**Issue by avi-mindinventory** [nao-pon/flysystem-google-drive#52]
Hey everyone,
I just got this email from google. IS this plugin going to be updated? OR is there one that uses Google Sign In instead of Google+ Sign In?
![g issue](https://user-images.githubusercontent.com/37392647/51983339-6f3a7900-24be-11e9-85b2-95cd2217c3b9.jpg)

**Comment by nao-pon** [comment]
@avi-mindinventory That's about Google_Client, , please ask at that developer or community.
