### ISSUE TITLE
Cache issues

### ISSUE THREAD

**Issue by buelna** [nao-pon/flysystem-google-drive#53]
Greetings!
I would like to know, is it possible to add a config for disabling the use of cache? since i'm having trouble with files with the same names that are supposed to be uploaded to different drive folders not being uploaded properly, and i get the files in another folder being replaced instead, i detected that i has to do with the files cached in the adapter, since removing the lookup into the cache while uploading a new file solved the issue (while working locally on my machine).

Thanks in advance for your answer!

**Comment by nao-pon** [comment]
@buelna The cause of this problem is in the way of creating the cache so I will fix this.

Thanks! 👍

**Comment by buelna** [comment]
Thanks, really useful, this way i don't have any missing files anymore haha
