### ISSUE TITLE
New Version Release?

### ISSUE THREAD

**Issue by DynamoGeek** [nao-pon/flysystem-google-drive#56]
Hello Nao-pon!

My team is currently being affected by an issue fixed in a recent PR request. Would you be able to tag a new version for release that included the recent fix?

Thanks in advance for any help you can provide!

~Justin

**Comment by nao-pon** [comment]
I released version [1.1.11](https://github.com/nao-pon/flysystem-google-drive/releases/tag/1.1.11). Thanks!
