### ISSUE TITLE
refresh token must be passed in or set as part of setAccessToken

### ISSUE THREAD

**Issue by hlo2109** [nao-pon/flysystem-google-drive#59]
The idea is to use drive as storage but I get that error from the token:

**refresh token must be passed in or set as part of setAccessToken**

`<?php 
$this->folder_id = env('GOOGLE_DRIVE_FOLDER_ID');
        $this->ClientId  = env('GOOGLE_DRIVE_CLIENT_ID');
        $this->ClientSecret = env('GOOGLE_DRIVE_CLIENT_SECRET');
        $this->refreshToken = env('GOOGLE_DRIVE_REFRESH_TOKEN');

        $this->client = new \Google_Client();
        $this->client->setClientId($this->ClientId);
        $this->client->setClientSecret($this->ClientSecret);
        $this->client->refreshToken($this->refreshToken);
        $this->service = new `\Google_Service_Drive($this->client);`
?>`

**Comment by nao-pon** [comment]
Probably the value of the refresh token is incorrect.
