### ISSUE TITLE
Unable to create file with / in name

### ISSUE THREAD

**Issue by aaronhuisinga** [nao-pon/flysystem-google-drive#61]
Currently when trying to create a file or folder with a forward slash (/) in the file name, it is not created successfully. This is due to the adapter treating the forward slash like it is a directory.

There should be some way to escape the forward slash so that it is properly stored as the file title on Google Drive. For example, "Today is 8\/26" would be stored as "Today is 8/26".

In the splitPath method of the GoogleDriveAdapter class, some changes could be made to allow for escaping of these characters.
Changing the `$paths = explode('/', $path);` on line 825 to `$paths = preg_split('|(?<!\\\)/|', $path);` would allow escaped backslashes to be skipped. 
We would also need to then filter the escaped slashes from the return:
```
return [
    $dirName,
    $fileName
];
```
would become
```
return [
    str_replace('\\/', '', $dirName),
    str_replace('\\/', '', $fileName)
];
```

**Comment by nao-pon** [comment]
Because "Util :: normalizePath ()" removes backslashes and non-printing characters, we need to define a forward slash substitute using printable characters and use it.

Therefore, please define an optional substitute character in the constant "EXT_FLYSYSTEM_SLASH_SUBSTITUTE" as needed.

ex.
```php
define('EXT_FLYSYSTEM_SLASH_SUBSTITUTE', '<:|sLASh|:>');
```

**Comment by achmadkhodzim** [comment]
> Because "Util :: normalizePath ()" removes backslashes and non-printing characters, we need to define a forward slash substitute using printable characters and use it.
> 
> Therefore, please define an optional substitute character in the constant "EXT_FLYSYSTEM_SLASH_SUBSTITUTE" as needed.
> 
> ex.
> 
> ```
> define('EXT_FLYSYSTEM_SLASH_SUBSTITUTE', '<:|sLASh|:>');
> ```
hi can you make an example on how to do it in laravel controller
i dont really understand what you mean here

**Comment by Atmden** [comment]
Hello! Sorry, but I don’t understand what to do.
In Google Chrome v 59.0.3071.115 - everything is fine
In Mozilla and Google Chrome latest version files are downloaded with a slash.
Please help me!
