### ISSUE TITLE
Google Batch Request deprecated

### ISSUE THREAD

**Issue by SebTorres** [nao-pon/flysystem-google-drive#78]
Google has [deprecated use of batch requests](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html?utm_campaign=ei-jun23&utm_medium=api-error-message&utm_source=shared_proxy). This in turn means that any call to the `getFileObject` function fails today, and will fail completely after August 12th.

**Comment by underthecocotree** [comment]
We seem to face the same issue without even using the getFileObject.

**Comment by nao-pon** [comment]
I will fix this. Thanks for your information.

**Comment by nao-pon** [comment]
@SebTorres , @underthecocotree I have committed this fix to master branch. Can you verify that?

**Comment by SebTorres** [comment]
It seems to have been fixed. I will do a more thorough testing at the end of the week to confirm. Thank you!

**Comment by underthecocotree** [comment]
The batch error has stopped but the file does not upload to the drive anymore.  Any ideas?

```
[0] => {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: filename.pptx.",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: filename.pptx."
 }
}
```

**Comment by underthecocotree** [comment]
Thanks for the quick fix @nao-pon.  I did a pull-request https://github.com/nao-pon/flysystem-google-drive/pull/80
 with a possible fix .

This is the code that we have been using without any problems up to now.
```
$stream = fopen($this->files[$this->file_id]['tmp_name'], 'r+');

$response = $this->filesystem->putStream(
  $this->getNewFilename(),
    $stream,
    [
        'mimetype' => 'application/vnd.google-apps.presentation',
    ]
);
```

As far as I am aware Google is phasing the support for the batch, that might be the reason that the old code can still work without an error at times.

**Comment by nao-pon** [comment]
@underthecocotree Thank you for sending the PR. I made some changes after merging it. Please check 4bdef433910d53663aff9506f26aeb4b94fe6dd8 for any operational problems.

**Comment by underthecocotree** [comment]
Looks great @nao-pon.  It all seems to working fine now.

**Comment by nao-pon** [comment]
@underthecocotree Thank you for verifying. After that, I modified it to version 1.1.13. If you find any problems, please let me know.
