### ISSUE TITLE
Basename gives id not full name of file/folder

### ISSUE THREAD

**Issue by Sare209** [nao-pon/flysystem-google-drive#8]
I want to get a list of the files/folders on a google drive. I used $filesystem->listContents();.
But if I for example have a folder called ‘1. Chapter 1’, I get this result:
_[type] => dir
[filename] => 1
[extension] =>  Chapter 1
[basename] => 0B25QkBaF5zNmTEREQ1o2b29hNWM
..._

The name gets split at the . because it thinks it’s the filename and the extension. Other adapters I’ve used do this as well, which I find weird because folders don’t have an extension.

Normally the basename should give me the full name of the file/folder so in this example ‘1. Chapter 1’. (This is the case for other adapters).
Your adapter gives the id of the file/folder so I can’t get the full name of a file/folder. Why do you give the id here? Is it possible to change this?

**Comment by nao-pon** [comment]
@Sare209 The item is managed by ID in GoogleDrive. Also, since item paths are not unique, IDs are indispensable to identify items.
If you need a full name please join filename and extention with a dot.
