### ISSUE TITLE
How to list files from shared with me ? 

### ISSUE THREAD

**Issue by odaiderawi** [nao-pon/flysystem-google-drive#84]

**Comment by PaolaRuby** [comment]
using files.list with the query string 'q'='sharedWithMe' because it only lists the children’s of Shared With Me

**Comment by w99910** [comment]
I tried as you mentioned but it didn't work as expected. The shared-files are not listed in returned collection. 
```php
$adapter = new GoogleDriveAdapter($service, 'root',['defaultParams' => ['files.list'=>['q'=>'sharedWithMe']],]);

$filesystem = new \League\Flysystem\Filesystem($adapter);

$filesystem->listContents('/', false));

```

**Comment by PaolaRuby** [comment]
It's wrong, I write it fine, read the docs
