### ISSUE TITLE
`getFileObject` by name works only if file is in `cacheFileObjectsByName`

### ISSUE THREAD

**Issue by matancohen365** [nao-pon/flysystem-google-drive#88]
Hey, 

I'm trying to determine if a file exists by its name.

Thats is my code:

```
<?php 

$gdrive = Storage::disk('google');

    if( ! $gdrive->exists('file.txt')) {

        $gdrive->put('file.txt', 'hello world!');
        
        var_dump($gdrive->exists('file.txt')); // true

    }
```

Every time I refresh the page, a new file created in my drive folder *** even if it already exists ***

After some debugging, I found the reason:

https://github.com/nao-pon/flysystem-google-drive/blob/bb812339ecf06540ed096f71403f10fcbcc590f3/src/GoogleDriveAdapter.php#L984

`getFileObject` *by name* works only if file is in `cacheFileObjectsByName`

So `$gdrive->exists('file.txt')` will work with a filename only after a `$gdrive->put('file.txt',..` request.

My workaround:
I'm using cache (filename => file key) but it's not reliable in the case of the file changed/deleted/removed.

Any idea how to fix it?

**Comment by nmfzone** [comment]
Of course you can't use `exists` with original file name. Google drive has its own file name and path (google allowed file with the same name), you need to use that to check your file exists or not.
