### ISSUE TITLE
How to get sheet data using sheet name in spreadsheet?

### ISSUE THREAD

**Issue by w99910** [nao-pon/flysystem-google-drive#96]
I'm trying to import sheet data using laravel excel package and the following is what I did before.
```php
\Maatwebsite\Excel\Facades\Excel::import(new \App\Imports\DataImport(), 'spreadsheetId', 'google', \Maatwebsite\Excel\Excel::XLSX); 
```
It loaded all data inside the spreadsheet. But what if I wanna load certain sheet inside the spreadsheet? 

In my google drive, I have 'abcdedfg' spread sheet and it has 'test' named sheet. How can I get data inside 'test' sheet? 

I have been finding the answer for so long but didn't find it yet.

**Comment by PaolaRuby** [comment]
This is a google drive package, only read, upload and download, you need a `\Google_Service_Sheets` package for that, look at this example [GoogleSheetsPathManager.php](https://github.com/private-it/flysystem-google-drive/blob/master/src/GoogleSheetsPathManager.php), also you can download all the file content, update it on local, and upload all the file content again, overwriting old file

**Comment by pankajthakur007** [comment]
@PaolaRuby  Can i create spreadsheet using nao-pon/flysystem-google-drive package? OR is there any package in laravel 8 for create spreadsheet

**Comment by PaolaRuby** [comment]
>This is a google drive package, only read, upload and download, you need a \Google_Service_Sheets package for that, look at this example GoogleSheetsPathManager.php, also you can download all the file content, update it on local, and upload all the file content again, overwriting old file

@pankajthakur007 Wow, I thought that I had made it clear that nao-pon/flysystem-google-drive package is not good for that, also I left an example of how to do it, you didn't even check it for sure, also there is `Google Search` and `Packagist` for package's search, this place is for flysystem-google-drive's issues

**Comment by w99910** [comment]
> This is a google drive package, only read, upload and download, you need a `\Google_Service_Sheets` package for that, look at this example [GoogleSheetsPathManager.php](https://github.com/private-it/flysystem-google-drive/blob/master/src/GoogleSheetsPathManager.php), also you can download all the file content, update it on local, and upload all the file content again, overwriting old file

Hi @PaolaRuby 
Sorry for late reply. I will try as you suggested. Thanks for your message. 
Best regards,
